name: web_app
description: A Flutter application with multiple webview tabs.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.7.0
  cupertino_icons: ^1.0.2
  image_picker: ^1.1.2
  http: ^1.3.0
  path: ^1.9.1
  logger: ^2.5.0
  flutter_dotenv: ^5.2.1
  model_viewer_plus: ^1.9.1
  path_provider: ^2.1.5
  shared_preferences: ^2.5.2
  json_annotation: ^4.9.0
  open_file: ^3.3.2
  flutter_easyloading: ^3.0.5
  flutter_image_compress: ^2.4.0
  dio: ^5.8.0+1
  crypto: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.15
  json_serializable: ^6.9.4
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/logo1.png
    - assets/logo2.png
    - assets/camera.png
    - assets/bg.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"  # 主图标路径
